# Generated by Django 2.2 on 2020-02-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_employee_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residents',
            old_name='city',
            new_name='tower',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_image',
        ),
    ]
