# Generated by Django 2.2 on 2020-02-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0005_remove_attendance_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='flat_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('24 hours', '24 hours'), ('12 hours', '12 hours'), ('part_time', 'part_time')], max_length=10, null=True),
        ),
    ]
