# Generated by Django 2.2 on 2020-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0006_auto_20200211_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='flat_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
