# Generated by Django 2.2 on 2020-02-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0007_auto_20200211_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
    ]
